
pipeline: hapflk

resources:
  conda_env: py27


steps:
  DEW-DWL:
    run:
      - source activate <conda_env>
      - hapflk --bfile <base_dir/>hapflk_dew_dwl/dew_dwl --kinship <base_dir/>hapflk_dew_dwl/dew_dwl_fij.txt -K 10 --ncpu=<cpu> --annot --nfit=50 --chr <sample> -p DEW-DWL.<sample>
    cpu: 64

  DWL-DWC:
    run:
      - source activate <conda_env>
      - hapflk --bfile <base_dir/>hapflk_dwl_dwc/dwl_dwc --kinship <base_dir/>hapflk_dwl_dwc/dwl_dwc_fij.txt -K 10 --ncpu=<cpu> --annot --nfit=50 --chr <sample> -p DWL-DWC.<sample>